title: Rodoblog
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   Blog de prueba de rodoviario

# social links
github_username:  rodoviario

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
